version: '3.9'

services:
  db:
    container_name: perf-db
    image: mysql
    restart: always
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'webUser'
      MYSQL_PASSWORD: 'webPass'
      MYSQL_ROOT_PASSWORD: 'password'
    networks:
      - internal

networks:
  internal:
